version: 1.0.0.0
github: tek/chiasma
license: BSD-2-Clause-Patent
license-file: LICENSE
author: Torsten Schmits
maintainer: haskell@tryp.io
copyright: 2022 Torsten Schmits
category: Terminal
build-type: Simple
extra-source-files:
  - readme.md
  - changelog.md
